# Generated by Django 2.2.7 on 2020-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_Mail', models.TextField(max_length=300, verbose_name='Поле для текста')),
            ],
        ),
    ]
