# Generated by Django 2.2.7 on 2020-03-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyForm',
        ),
    ]
